version: "3.3"
services:
  nginx:
    image: nginx:latest
    deploy:
      restart_policy:
        condition: on-failure

    volumes:
      - /home/ubuntu/IUPAT-dev-servers/docker_youtrack/certs:/opt/youtrack/certs
      - /home/ubuntu/IUPAT-dev-servers/docker_youtrack/nginx/yt_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - yt_net


  youtrack:
    image: jetbrains/youtrack:2018.4.48406
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /home/ubuntu/IUPAT-dev-servers/docker_youtrack/youtrack/data:/opt/youtrack/data
      - /home/ubuntu/IUPAT-dev-servers/docker_youtrack/youtrack/conf:/opt/youtrack/conf
      - /home/ubuntu/IUPAT-dev-servers/docker_youtrack/youtrack/logs:/opt/youtrack/logs
      - /home/ubuntu/IUPAT-dev-servers/docker_youtrack/youtrack/backup:/opt/youtrack/backups
    ports:
      - 8080:8080
    networks:
      - yt_net

networks:
  yt_net:
