version: "3.3"
services:
  nginx:
    container_name: yt_nginx
    image: nginx:latest
    restart: unless-stopped

    volumes:
      - ./certs:/opt/youtrack/certs
      - ./nginx/yt_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  youtrack:
    container_name: youtrack
    image: jetbrains/youtrack:2018.4.48406
    restart: unless-stopped
    volumes:
      - ./youtrack/data:/opt/youtrack/data
      - ./youtrack/conf:/opt/youtrack/conf
      - ./youtrack/logs:/opt/youtrack/logs
      - ./youtrack/backup:/opt/youtrack/backups
    ports:
      - 8080:8080