version: "2"
services:
  nginx:
    container_name: tc_nginx
    image: nginx:latest
    restart: unless-stopped

    volumes:
      - ./certs:/opt/nginx/certs
      - ./nginx/tc_default.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: US/Mountain

  teamcity:
    container_name: teamcity
    image: jetbrains/teamcity-server
    restart: unless-stopped
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/logs:/opt/teamcity/logs
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8111:8111
    environment:
      TZ: US/Mountain

#uncomment for local agent
#  agent_007:
#    build:
#      context: ./javaAgent
#      dockerfile: ./JavaAgent
#    image: javaagent
#    cpu_quota: 66000
#    restart: unless-stopped
#    volumes:
#      - ./teamcity/agent007Config:/data/teamcity_agent/conf
#      - /etc/timezone:/etc/timezone:ro
#    environment:
#      SERVER_URL: teamcity:8111
#      TZ: US/Mountain
#      AGENT_NAME: Agent 007

#uncomment for local 2nd agent
#  agent_smith:
#    image: javaagent
#    depends_on:
#      - agent_007
#    cpu_quota: 66000
#    restart: unless-stopped
#    volumes:
#      - ./teamcity/agentSmithConfig:/data/teamcity_agent/conf
#      - /etc/timezone:/etc/timezone:ro
#    environment:
#      SERVER_URL: teamcity:8111
#      TZ: US/Mountain
#      AGENT_NAME: Agent Smith

#Change the password to something secure
  db:
    container_name: tc_postgres
    build:
      context: ./teamcityPsql
      dockerfile: ./teamcityPostgresDockerfile
    image: tc_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      TZ: US/Mountain
    volumes:
      - ./teamcity/db_data/db:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
