version: "2"
services:
  nginx:
    container_name: tc_nginx
    image: nginx:latest
    restart: unless-stopped

    volumes:
      - ./certs:/opt/nginx/certs
      - ./nginx/tc_default.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: US/Mountain

  teamcity:
    container_name: teamcity
    image: jetbrains/teamcity-server
    restart: unless-stopped
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/logs:/opt/teamcity/logs
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8111:8111
    environment:
      TZ: US/Mountain

  tc_agent_1:
    build:
      context: ./javaAgent
      dockerfile: ./JavaAgent
    image: javaagent
    cpu_quota: 66000
    restart: unless-stopped
    volumes:
      - ./teamcity/agentConfig_1:/data/teamcity_agent/conf
      - /etc/timezone:/etc/timezone:ro
    environment:
      SERVER_URL: teamcity:8111
      TZ: US/Mountain

  tc_agent_2:
    image: javaagent
    depends_on:
      - tc_agent_1
    cpu_quota: 66000
    restart: unless-stopped
    volumes:
      - ./teamcity/agentConfig_2:/data/teamcity_agent/conf
      - /etc/timezone:/etc/timezone:ro
    environment:
      SERVER_URL: teamcity:8111
      TZ: US/Mountain


  db:
    container_name: tc_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      TZ: US/Mountain
    volumes:
      - ./teamcity/db_data/db:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
