version: "2"
services:
  nginx:
    container_name: tc_nginx
    image: nginx:latest
    restart: unless-stopped

    volumes:
      - ./certs:/opt/nginx/certs
      - ./nginx/tc_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  teamcity:
    container_name: teamcity
    image: jetbrains/teamcity-server
    restart: unless-stopped
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/logs:/opt/teamcity/logs
    ports:
      - 8111:8111

  tc_agent:
    container_name: tc_agent
    image: jetbrains/teamcity-agent
    cpu_quota: 66000
    restart: unless-stopped
    volumes:
      - ./teamcity/agentConfig:/data/teamcity_agent/conf
    environment:
      SERVER_URL: teamcity:8111

  db:
    container_name: tc_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
    volumes:
      - ./teamcity/db_data:/var/lib/postgresql/data
